# Generated by Django 4.2.16 on 2024-11-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_profile_image_user_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.CharField(blank=True, choices=[('sports', '스포츠'), ('travel', '여행'), ('cook', '요리'), ('food', '맛집탐방'), ('fashion', '패션'), ('books', '독서'), ('music', '음악'), ('friends', '사교'), ('etc', '이외')], max_length=20, null=True),
        ),
    ]
